import { ClauseInput } from '../../domain/agreements/template';

/**
 * Built-in India residential clause set. Used when no DB template/clause library
 * is seeded, so agreements render out of the box. NOT counsel-reviewed.
 */
export const DEFAULT_RESIDENTIAL_CLAUSES: ClauseInput[] = [
  {
    key: 'parties',
    title: 'Parties',
    body: 'This rental agreement is made between {{landlordName}} ("Landlord") and {{tenantName}} ("Tenant") in respect of the premises at {{propertyAddress}}.',
  },
  {
    key: 'term',
    title: 'Term',
    body: 'The tenancy is for a term of {{termMonths}} months commencing on {{startDate}}.',
  },
  {
    key: 'rent',
    title: 'Rent',
    body: 'The monthly rent is {{monthlyRent}}, payable on or before day {{billingDay}} of each calendar month.',
  },
  {
    key: 'deposit',
    title: 'Security Deposit',
    body: 'The Tenant has paid a refundable interest-free security deposit of {{deposit}}, to be returned at the end of the tenancy after lawful deductions.',
  },
  {
    key: 'escalation',
    title: 'Rent Escalation',
    body: 'The rent shall be revised on each anniversary of the commencement date in accordance with the agreed escalation schedule.',
  },
  {
    key: 'maintenance',
    title: 'Maintenance',
    body: 'Routine, day-to-day maintenance shall be borne by the Tenant; major and structural repairs shall be borne by the Landlord.',
  },
  {
    key: 'notice',
    title: 'Notice Period',
    body: 'Either party may terminate this agreement by giving {{noticePeriodDays}} days prior written notice to the other.',
  },
  {
    key: 'house_rules',
    title: 'House Rules',
    body: 'The Tenant agrees to abide by the house rules in force for the property, as amended from time to time.',
  },
  {
    key: 'governing_law',
    title: 'Governing Law & Disclaimer',
    body: 'This agreement is governed by the laws applicable in {{jurisdiction}}. It is generated by RentLedger from configurable templates and is NOT legal advice; it requires review by qualified counsel before execution.',
  },
];
